"""Add no match flag to badge template

Revision ID: 00896e1a9eaa
Revises: ab1e65b9bf15
Create Date: 2019-01-14 07:28:59.568797

"""

# revision identifiers, used by Alembic.
revision = '00896e1a9eaa'
down_revision = 'ab1e65b9bf15'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge_template', sa.Column('no_match', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge_template', 'no_match')
    # ### end Alembic commands ###
