"""Initial models

Revision ID: 732a37f938ea
Revises: None
Create Date: 2019-01-06 16:14:06.551073

"""

# revision identifiers, used by Alembic.
revision = '732a37f938ea'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_template',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('extends_id', sa.BigInteger(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('image', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['extends_id'], ['badge_template.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_template_created_at'), 'badge_template', ['created_at'], unique=False)
    op.create_index(op.f('ix_badge_template_updated_at'), 'badge_template', ['updated_at'], unique=False)
    op.create_table('flag',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Unicode(length=128), nullable=False),
    sa.Column('password', sa.VARBINARY(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_table('badge',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('foreign_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('real_age', sa.Integer(), nullable=True),
    sa.Column('under_18', sa.Boolean(), nullable=False),
    sa.Column('under_13', sa.Boolean(), nullable=False),
    sa.Column('print_queued', sa.Boolean(), nullable=False),
    sa.Column('print_queued_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['print_queued_by_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foreign_id')
    )
    op.create_index(op.f('ix_badge_created_at'), 'badge', ['created_at'], unique=False)
    op.create_index(op.f('ix_badge_print_queued'), 'badge', ['print_queued'], unique=False)
    op.create_index(op.f('ix_badge_updated_at'), 'badge', ['updated_at'], unique=False)
    op.create_table('badge_template_to_flag',
    sa.Column('badge_template_id', sa.BigInteger(), nullable=False),
    sa.Column('flag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['badge_template_id'], ['badge_template.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_template_id', 'flag_id')
    )
    op.create_table('badge_print',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.BigInteger(), nullable=False),
    sa.Column('queued_by_id', sa.BigInteger(), nullable=True),
    sa.Column('printed_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printed_by_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queued_by_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_print_created_at'), 'badge_print', ['created_at'], unique=False)
    op.create_index(op.f('ix_badge_print_updated_at'), 'badge_print', ['updated_at'], unique=False)
    op.create_table('badge_to_flag',
    sa.Column('badge_id', sa.BigInteger(), nullable=False),
    sa.Column('flag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_id', 'flag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_to_flag')
    op.drop_table('badge_print')
    op.drop_table('badge_template_to_flag')
    op.drop_table('badge')
    op.drop_table('user')
    op.drop_table('flag')
    op.drop_table('badge_template')
    # ### end Alembic commands ###
