"""Additional position fields

Revision ID: ab1e65b9bf15
Revises: d6f925353a45
Create Date: 2019-01-09 08:46:38.543536

"""

# revision identifiers, used by Alembic.
revision = 'ab1e65b9bf15'
down_revision = 'd6f925353a45'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge_template', sa.Column('arbitrary_text_override_level', sa.Boolean(), nullable=False))
    op.add_column('badge_template', sa.Column('timestamp_append_to_level', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge_template', 'timestamp_append_to_level')
    op.drop_column('badge_template', 'arbitrary_text_override_level')
    # ### end Alembic commands ###
