"""Badge element position fields

Revision ID: d6f925353a45
Revises: e4b2f492f023
Create Date: 2019-01-09 08:12:03.288882

"""

# revision identifiers, used by Alembic.
revision = 'd6f925353a45'
down_revision = 'e4b2f492f023'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge_template', sa.Column('arbitrary_text', sa.UnicodeText(), nullable=True))
    op.add_column('badge_template', sa.Column('arbitrary_text_height', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('arbitrary_text_left', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('arbitrary_text_top', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('arbitrary_text_width', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_name_height', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_name_left', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_name_top', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_name_width', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_number_height', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_number_left', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_number_top', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('badge_number_width', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('css', sa.UnicodeText(), nullable=True))
    op.add_column('badge_template', sa.Column('level_height', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('level_left', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('level_top', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('level_width', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('timestamp_format', sa.UnicodeText(), nullable=True))
    op.add_column('badge_template', sa.Column('timestamp_height', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('timestamp_left', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('timestamp_top', sa.Float(), nullable=True))
    op.add_column('badge_template', sa.Column('timestamp_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge_template', 'timestamp_width')
    op.drop_column('badge_template', 'timestamp_top')
    op.drop_column('badge_template', 'timestamp_left')
    op.drop_column('badge_template', 'timestamp_height')
    op.drop_column('badge_template', 'timestamp_format')
    op.drop_column('badge_template', 'level_width')
    op.drop_column('badge_template', 'level_top')
    op.drop_column('badge_template', 'level_left')
    op.drop_column('badge_template', 'level_height')
    op.drop_column('badge_template', 'css')
    op.drop_column('badge_template', 'badge_number_width')
    op.drop_column('badge_template', 'badge_number_top')
    op.drop_column('badge_template', 'badge_number_left')
    op.drop_column('badge_template', 'badge_number_height')
    op.drop_column('badge_template', 'badge_name_width')
    op.drop_column('badge_template', 'badge_name_top')
    op.drop_column('badge_template', 'badge_name_left')
    op.drop_column('badge_template', 'badge_name_height')
    op.drop_column('badge_template', 'arbitrary_text_width')
    op.drop_column('badge_template', 'arbitrary_text_top')
    op.drop_column('badge_template', 'arbitrary_text_left')
    op.drop_column('badge_template', 'arbitrary_text_height')
    op.drop_column('badge_template', 'arbitrary_text')
    # ### end Alembic commands ###
