"""Levels

Revision ID: e4b2f492f023
Revises: 732a37f938ea
Create Date: 2019-01-08 08:41:34.591561

"""

# revision identifiers, used by Alembic.
revision = 'e4b2f492f023'
down_revision = '732a37f938ea'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('badge_template_to_level',
    sa.Column('badge_template_id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['badge_template_id'], ['badge_template.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_template_id', 'level_id')
    )
    op.add_column('badge', sa.Column('level_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'badge', 'level', ['level_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badge', type_='foreignkey')
    op.drop_column('badge', 'level_id')
    op.drop_table('badge_template_to_level')
    op.drop_table('level')
    # ### end Alembic commands ###
